/* MENUO production authentication: Supabase Auth, email/password, recovery and OAuth. */
(function(){
  'use strict';
  const PROD_SITE='https://ant1kgfhfhn.github.io/menuoproject/';
  const SITE=/^(localhost|127\\.0\\.0\\.1)$/.test(location.hostname)?location.origin+location.pathname:PROD_SITE;
  function sb(){return window.MENUO_SUPABASE||null}
  function localState(){try{return typeof state!=='undefined'?state:null}catch(_){return null}}
  function saveLocal(){try{if(typeof save==='function')save()}catch(_){} }
  function notice(msg){const e=document.getElementById('authError');if(e){e.textContent=msg;e.classList.remove('hidden')}}
  function clearNotice(){const e=document.getElementById('authError');if(e){e.textContent='';e.classList.add('hidden')}}
  function localUserByEmail(email){const s=localState();return s?.users?.find(u=>String(u.email||'').toLowerCase()===String(email||'').toLowerCase())||null}
  function syncLocalUser(su){const s=localState();if(!s||!su)return;const meta=su.user_metadata||{};let u=s.users?.find(x=>x.id===su.id)||localUserByEmail(su.email);const oldId=u?.id;if(!u){u={id:su.id,firstName:String(meta.first_name||meta.firstName||meta.name||'').split(' ')[0]||'Пользователь',lastName:String(meta.last_name||meta.lastName||meta.name||'').split(' ').slice(1).join(' '),email:su.email||'',plan:'FREE'};s.users=s.users||[];s.users.push(u)}else{u.id=su.id;u.email=su.email||u.email;u.firstName=u.firstName||meta.first_name||meta.firstName||'Пользователь';u.lastName=u.lastName||meta.last_name||meta.lastName||'';u.plan=u.plan||'FREE';if(oldId&&oldId!==su.id){(s.restaurants||[]).forEach(r=>{if(r.ownerId===oldId)r.ownerId=su.id});if(s.session===oldId)s.session=su.id}}s.session=su.id;saveLocal()}
  async function hydrateProfile(su){try{const c=sb();if(!c||!su)return;const q=await c.from('profiles').select('first_name,last_name').eq('id',su.id).maybeSingle();const p=q.data;const s=localState();const u=s?.users?.find(x=>x.id===su.id);if(u&&p){u.firstName=p.first_name||u.firstName;u.lastName=p.last_name||u.lastName;saveLocal()}}catch(_){} }
  async function ensureSession(){const c=sb();if(!c)return null;const {data:{session}}=await c.auth.getSession();if(session?.user){syncLocalUser(session.user);await hydrateProfile(session.user)}return session}
  function addSocialButtons(){const submit=document.getElementById('authSubmit');if(!submit||document.getElementById('menuoSocial'))return;const box=document.createElement('div');box.id='menuoSocial';box.innerHTML=`<div style="display:flex;align-items:center;gap:10px;margin:18px 0;color:#69756e;font-size:12px"><span style="height:1px;background:#e3e9e5;flex:1"></span><span>или</span><span style="height:1px;background:#e3e9e5;flex:1"></span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px"><button type="button" id="menuoGoogle" class="secondary">G&nbsp; Google</button><button type="button" id="menuoApple" class="secondary"> Apple</button></div><button type="button" id="menuoMagic" class="textbtn" style="display:block;margin:13px auto 0">Получить ссылку на email</button>`;submit.insertAdjacentElement('afterend',box);box.querySelector('#menuoGoogle').onclick=()=>oauth('google');box.querySelector('#menuoApple').onclick=()=>oauth('apple');box.querySelector('#menuoMagic').onclick=magicLink}
  async function oauth(provider){const c=sb();if(!c)return notice('Система авторизации ещё загружается. Попробуйте через секунду.');const options={redirectTo:SITE};if(provider==='google')options.scopes='https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile';const {error}=await c.auth.signInWithOAuth({provider,options});if(error){if(error.code==='provider_disabled'||/provider is not enabled/i.test(error.message||''))return notice(`Вход через ${provider==='google'?'Google':'Apple'} пока не включён в настройках Supabase. Код приложения уже готов, нужно включить провайдер и добавить его Client ID/Secret.`);notice(error.message||'Не удалось открыть вход.')}}
  async function magicLink(){clearNotice();const email=document.getElementById('authEmail').value.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return notice('Сначала укажите email.');const c=sb();if(!c)return notice('Система авторизации ещё загружается.');const {error}=await c.auth.signInWithOtp({email,options:{emailRedirectTo:SITE}});if(error){if(error.code==='over_email_send_rate_limit'||/rate limit/i.test(error.message||''))return notice('Письма временно ограничены Supabase. Подождите до 1 часа или подключите собственный SMTP для MENUO.');return notice(error.message)}notice('Ссылка для входа отправлена на email. Проверьте почту и папку «Спам».')}
  async function submit(){clearNotice();const c=sb();if(!c)return notice('Система авторизации ещё загружается.');const email=document.getElementById('authEmail').value.trim().toLowerCase();const pass=document.getElementById('authPassword').value;if(!/^\S+@\S+\.\S+$/.test(email))return notice('Введите корректный email.');if(pass.length<8)return notice('Пароль должен содержать минимум 8 символов.');const mode=window.__MENUO_AUTH_MODE||'login';const b=document.getElementById('authSubmit');b.disabled=true;try{let result;if(mode==='register'){const first=document.getElementById('firstName').value.trim(),last=document.getElementById('lastName').value.trim(),confirm=document.getElementById('confirmPassword').value;if(!first||!last)throw new Error('Введите имя и фамилию.');if(pass!==confirm)throw new Error('Пароли не совпадают.');result=await c.auth.signUp({email,password:pass,options:{data:{first_name:first,last_name:last},emailRedirectTo:SITE}});if(result.error)throw result.error;if(result.data.session?.user){syncLocalUser(result.data.session.user);await hydrateProfile(result.data.session.user);return finishAuth()}notice('Аккаунт создан. Подтвердите email по ссылке из письма, затем войдите.')}else{result=await c.auth.signInWithPassword({email,password:pass});if(result.error)throw result.error;syncLocalUser(result.data.user);await hydrateProfile(result.data.user);finishAuth()}}catch(e){notice(e.message||'Не удалось выполнить вход.')}finally{b.disabled=false}}
  function finishAuth(){const after=window.__MENUO_AUTH_AFTER||'home';window.__MENUO_AUTH_AFTER='home';if(after==='owner')show('owner');else show('home')}
  async function reset(){const n=document.getElementById('resetNotice');n.classList.add('hidden');const email=document.getElementById('resetEmail').value.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)){n.textContent='Введите корректный email.';n.classList.remove('hidden');return}const c=sb();if(!c){n.textContent='Система авторизации ещё загружается.';n.classList.remove('hidden');return}const b=document.querySelector('#resetNotice')?.parentElement?.querySelector('button.primary');if(b){b.disabled=true;b.dataset.originalText=b.textContent;b.textContent='Подождите…'}try{const {error}=await c.auth.resetPasswordForEmail(email,{redirectTo:SITE+'?auth=recovery'});if(error){if(error.code==='over_email_send_rate_limit'||/rate limit/i.test(error.message||''))n.textContent='Supabase временно ограничил отправку писем. Это не ошибка вашего аккаунта. Подождите до 1 часа. Для production MENUO лучше подключить собственный SMTP — тогда лимит 2 письма/час встроенного сервиса не будет узким местом.';else n.textContent=error.message}else n.textContent='Если такой аккаунт существует, письмо для сброса пароля отправлено. Проверьте почту и «Спам».';n.classList.remove('hidden')}finally{if(b){b.disabled=false;b.textContent=b.dataset.originalText||'Получить код'}}}
  function recoveryScreen(){let el=document.getElementById('menuoRecovery');if(el)return;el=document.createElement('section');el.id='menuoRecovery';el.className='screen';el.innerHTML=`<div class="top"><button class="back" id="menuoRecoveryBack">‹</button><div class="brand">Новый пароль</div><span></span></div><div class="hero" style="padding-top:3vh"><div class="eyebrow">Восстановление</div><h1 class="section-title">Придумайте новый пароль</h1><p class="lead">Минимум 8 символов. После сохранения вы снова сможете войти в MENUO.</p><div id="menuoRecoveryError" class="notice error hidden"></div><div class="field"><label>Новый пароль</label><input id="menuoNewPassword" type="password" minlength="8" autocomplete="new-password"></div><div class="field"><label>Повторите пароль</label><input id="menuoNewPassword2" type="password" minlength="8" autocomplete="new-password"></div><button class="primary" id="menuoRecoverySave">Сохранить новый пароль</button></div>`;document.getElementById('app').appendChild(el);el.querySelector('#menuoRecoveryBack').onclick=()=>show('home');el.querySelector('#menuoRecoverySave').onclick=async()=>{const a=el.querySelector('#menuoNewPassword').value,b=el.querySelector('#menuoNewPassword2').value,e=el.querySelector('#menuoRecoveryError');e.classList.add('hidden');if(a.length<8){e.textContent='Пароль должен содержать минимум 8 символов.';e.classList.remove('hidden');return}if(a!==b){e.textContent='Пароли не совпадают.';e.classList.remove('hidden');return}const {error}=await sb().auth.updateUser({password:a});if(error){e.textContent=error.message;e.classList.remove('hidden');return}alert('Пароль изменён.');history.replaceState({},'',SITE);await ensureSession();finishAuth()};show('menuoRecovery')}
  function patch(){const oldOpenAuth=window.openAuth;window.openAuth=function(mode='login',after='home'){window.__MENUO_AUTH_MODE=mode;window.__MENUO_AUTH_AFTER=after;if(typeof oldOpenAuth==='function')oldOpenAuth(mode,after);else show('auth');addSocialButtons()};window.submitAuth=submit;window.resetPassword=reset;window.openOwner=async function(){const s=await ensureSession();if(s?.user){show('owner');return}window.openAuth('login','owner')};window.openProfile=async function(){const s=await ensureSession();if(s?.user){show('userProfile');return}window.openAuth('login','home')};window.openSubscription=async function(){const s=await ensureSession();if(s?.user){show('subscription');return}window.openAuth('login','home')};window.logout=async function(){const c=sb();if(c)await c.auth.signOut();const s=localState();if(s){s.session=null;s.activeRestaurantId=null;saveLocal()}show('home')};const c=sb();if(c){c.auth.onAuthStateChange(async(event,session)=>{if(session?.user){syncLocalUser(session.user);if(event!=='INITIAL_SESSION')await hydrateProfile(session.user)}if(event==='PASSWORD_RECOVERY')recoveryScreen()});ensureSession()}if(new URLSearchParams(location.search).get('auth')==='recovery')setTimeout(()=>{if(sb())recoveryScreen()},500)}
  const timer=setInterval(()=>{if(sb()){clearInterval(timer);patch()}},50);setTimeout(()=>{if(!sb())clearInterval(timer)},15000)
})();
