create extension if not exists pgcrypto;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,locale text not null default 'ru',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.plans(id text primary key,name text not null,price_monthly_cents integer not null default 0 check(price_monthly_cents>=0),max_restaurants integer,max_dishes_per_restaurant integer,max_qr_codes integer,allergens boolean not null default false,multilingual boolean not null default false,analytics boolean not null default false,branches boolean not null default false,promos boolean not null default false,created_at timestamptz not null default now());
insert into public.plans(id,name,price_monthly_cents,max_restaurants,max_dishes_per_restaurant,max_qr_codes,allergens,multilingual,analytics,branches,promos) values ('free','FREE',0,1,10,1,false,false,false,false,false),('pro','PRO',999,2,null,2,true,true,true,false,false),('business','BUSINESS',1999,null,null,null,true,true,true,true,true) on conflict(id) do update set name=excluded.name,price_monthly_cents=excluded.price_monthly_cents,max_restaurants=excluded.max_restaurants,max_dishes_per_restaurant=excluded.max_dishes_per_restaurant,max_qr_codes=excluded.max_qr_codes,allergens=excluded.allergens,multilingual=excluded.multilingual,analytics=excluded.analytics,branches=excluded.branches,promos=excluded.promos;
create table if not exists public.subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id) on delete cascade,plan_id text not null references public.plans(id),status text not null default 'active' check(status in('trialing','active','past_due','canceled','incomplete')),stripe_customer_id text,stripe_subscription_id text,current_period_start timestamptz,current_period_end timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.restaurants(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,name text not null check(char_length(trim(name)) between 1 and 120),slug text not null unique check(slug ~ '^[a-z0-9][a-z0-9-]{2,79}$'),logo_url text,address text,phone text,description text,website text,instagram text,facebook text,hours jsonb not null default '{}'::jsonb,default_locale text not null default 'ru',published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,name text not null check(char_length(trim(name)) between 1 and 80),sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now(),unique(restaurant_id,name));
create table if not exists public.dishes(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.restaurants(id) on delete cascade,category_id uuid references public.categories(id) on delete set null,name text not null check(char_length(trim(name)) between 1 and 120),description text not null default '',price_cents integer not null check(price_cents between 0 and 100000000),currency char(3) not null default 'EUR',image_url text,is_available boolean not null default true,sort_order integer not null default 0,allergens text[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.dish_translations(dish_id uuid not null references public.dishes(id) on delete cascade,locale text not null,name text not null,description text not null default '',primary key(dish_id,locale));
create table if not exists public.qr_codes(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null unique references public.restaurants(id) on delete cascade,token text not null unique default encode(gen_random_bytes(18),'base64url'),name text not null default 'Основной QR',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.analytics_events(id bigint generated always as identity primary key,restaurant_id uuid not null references public.restaurants(id) on delete cascade,qr_code_id uuid references public.qr_codes(id) on delete set null,event_type text not null check(event_type in('menu_view','qr_scan')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists restaurants_owner_idx on public.restaurants(owner_id); create index if not exists categories_restaurant_idx on public.categories(restaurant_id,sort_order); create index if not exists dishes_restaurant_idx on public.dishes(restaurant_id,sort_order); create index if not exists dishes_category_idx on public.dishes(category_id,sort_order); create index if not exists analytics_qr_code_idx on public.analytics_events(qr_code_id); create index if not exists subscriptions_plan_idx on public.subscriptions(plan_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,locale) values(new.id,new.raw_user_meta_data->>'full_name',coalesce(new.raw_user_meta_data->>'locale','ru')) on conflict(id) do nothing; insert into public.subscriptions(user_id,plan_id,status) values(new.id,'free','active') on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
create or replace function public.get_my_plan() returns text language sql stable security definer set search_path=public as $$ select coalesce((select plan_id from public.subscriptions where user_id=(select auth.uid()) and status in('trialing','active','past_due') limit 1),'free'); $$;
create or replace function public.get_public_menu(p_token text) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare r public.restaurants; result jsonb; begin select rr.* into r from public.restaurants rr join public.qr_codes q on q.restaurant_id=rr.id where q.token=p_token and q.is_active=true and rr.published=true limit 1; if not found then return null; end if; select jsonb_build_object('restaurant',jsonb_build_object('id',r.id,'name',r.name,'slug',r.slug,'logo_url',r.logo_url,'address',r.address,'phone',r.phone,'description',r.description,'website',r.website,'instagram',r.instagram,'facebook',r.facebook,'hours',r.hours,'default_locale',r.default_locale),'categories',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'sort_order',c.sort_order) order by c.sort_order,c.created_at) from public.categories c where c.restaurant_id=r.id and c.is_active=true),'[]'::jsonb),'dishes',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'category_id',d.category_id,'name',d.name,'description',d.description,'price_cents',d.price_cents,'currency',d.currency,'image_url',d.image_url,'is_available',d.is_available,'sort_order',d.sort_order,'allergens',d.allergens) order by d.sort_order,d.created_at) from public.dishes d where d.restaurant_id=r.id),'[]'::jsonb)) into result; return result; end; $$;
revoke execute on function public.handle_new_user() from public,anon,authenticated; revoke execute on function public.get_my_plan() from public,anon; revoke execute on function public.get_public_menu(text) from public,authenticated; grant execute on function public.get_my_plan() to authenticated; grant execute on function public.get_public_menu(text) to anon;

grant usage on schema public to anon,authenticated; grant select on public.plans to anon,authenticated; grant select,insert,update,delete on public.profiles,public.subscriptions,public.restaurants,public.categories,public.dishes,public.dish_translations,public.qr_codes to authenticated; grant insert on public.analytics_events to anon,authenticated;
alter table public.profiles enable row level security; alter table public.plans enable row level security; alter table public.subscriptions enable row level security; alter table public.restaurants enable row level security; alter table public.categories enable row level security; alter table public.dishes enable row level security; alter table public.dish_translations enable row level security; alter table public.qr_codes enable row level security; alter table public.analytics_events enable row level security;
create policy if not exists plans_public on public.plans for select using(true);
create policy if not exists profiles_self on public.profiles for all to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy if not exists subscriptions_self on public.subscriptions for select using(user_id=(select auth.uid()));
create policy if not exists subscriptions_self_update on public.subscriptions for update using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy if not exists restaurants_owner on public.restaurants for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy if not exists categories_owner on public.categories for all to authenticated using(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid()))) with check(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid())));
create policy if not exists dishes_owner on public.dishes for all to authenticated using(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid()))) with check(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid())));
create policy if not exists translations_owner on public.dish_translations for all to authenticated using(exists(select 1 from public.dishes d join public.restaurants r on r.id=d.restaurant_id where d.id=dish_id and r.owner_id=(select auth.uid()))) with check(exists(select 1 from public.dishes d join public.restaurants r on r.id=d.restaurant_id where d.id=dish_id and r.owner_id=(select auth.uid())));
create policy if not exists qr_owner on public.qr_codes for all to authenticated using(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid()))) with check(exists(select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid())));
create policy if not exists analytics_insert on public.analytics_events for insert to anon,authenticated with check(true);
